sequenceDiagram
  participant User
  participant Ember/Browser
  participant API
Note over User, API: Org is fixed with emberjs, all repositories are emberjs org's
User->>+Ember/Browser: /repositories/ember.js
Note over Ember/Browser: ApplicationRoute
Note over Ember/Browser: RepositoriesRoute
Ember/Browser->>API: GET /orgs/emberjs/repos
Note over Ember/Browser: RepositoryRoute
Ember/Browser->>API: GET /repos/emberjs/emberj.js
Note over Ember/Browser: RepositoryIndexRoute
Ember/Browser->>API: GET /repos/emberjs/ember.js/commits
Ember/Browser->>API: GET /repos/emberjs/ember.js/commits/b58..
Ember/Browser->>API: GET /repos/emberjs/ember.js/commits/af2..
Ember/Browser->>API: GET /repos/emberjs/ember.js/commits/c9d..
Ember/Browser->>API: GET /repos/emberjs/ember.js/commits/e1f..
Ember/Browser->>API: GET /repos/emberjs/ember.js/commits/c74..
Ember/Browser->>-User: Display
