graph TD
  Application==>Repositories[Repositories]
  Repositories-.-RepositoriesIndex[RepositorieyIndex]
  Repositories-.-RepositoriesNew[RepositoriewNew]
  Repositories==>Repository[Repository]
  Repository[Repository]-.-RepositoryIndex[RepositoryIndex]
  Repository[Repository]==>RepositoryEdit[RepositoryEdit]
