graph TD
  ApplicationRoute-->Repositories[RepositoriesRoute]
  Repositories-->Repository[RepositoriesRepositoryRoute]
  Repository[RepositoriesRepositoryRoute]-->RepositoryEdit[RepositoriesRepositoryEditRoute]
