graph TD
  Router[Routing /]
  Router-->ApplicationRoute[ApplicationRoute]
  ApplicationRoute--> |render application.hbs| IndexRoute[IndexRoute]
  IndexRoute-->|render index.hbs in outlet in application.hbs if it exists| END
